# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c0086137a1c16cda89be2fe6dfc11b2db07d5d853ab32b4d1b25e77419fb748178d172597b0c0aba5bb0fad9960903d1c54d92227081a9a34e9633def3e2191

test:
  secret_key_base: 8e0f98016e6ee43332136c65cc55688cc3fdd4030049d7f10ed9d03f0e50d8d09698a6e55a5d251db0f11ec6885c23ffc455c21985da780e18c83bf553931578

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
